services:
  - type: web
    name: TodoApp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn TodoApp.main:app --host 0.0.0.0 --port 10000"
    pythonVersion: 3.11.9