"""fix complete field

Revision ID: 0a508cc57a9f
Revises: 648864403e70
Create Date: 2026-01-23 18:07:49.668529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a508cc57a9f'
down_revision: Union[str, Sequence[str], None] = '648864403e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number2', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
